### ISSUE TITLE
Unsupported new ANON const CVs

### ISSUE THREAD

**Issue by atoomic** [rurban/perl-compiler#246] opened 2015-10-13 21:30 UTC
we probably do not want to support this, but we cannot compile a code using that experimental featureon 5.22

```perl
no warnings "experimental::const_attr";
print qq{ok\n} if &{sub () : const { 42 }} == 42;
```
````
> perl -e 'no warnings "experimental::const_attr"; print qq{ok\n} if &{sub () : const { 42 }} == 42;'
ok
> perlcc -e 'no warnings "experimental::const_attr"; print qq{ok\n} if &{sub () : const { 42 }} == 42;'
> ./a.out
Segmentation fault
````

**Comment by rurban** [comment] 2015-10-14 16:50
No we should

**Comment by toddr** [comment] 2015-10-29 20:47
./t/testc.sh 246

**Comment by rurban** [comment] 2015-11-14 07:19
This has nothing to do with experimental::const_attr.
Duplicate of #305

**Comment by rurban** [comment] 2015-11-14 08:12
anon const is just a CONSTSUB. This failed in earlier perl versions.
Fixed with `anonconst-gh246` 3c6ffa2 but this broke many other tests...

**Comment by rurban** [comment] 2015-11-14 10:29
Fixed in master with dfb0a35bace5d8bc9c6762b8568c926dfba96b07

**Closed by rurban** 2015-11-14 10:29 UTC
Labels: CoreTests.522, Priority-Low, Uses New Feature
