### ISSUE TITLE
Features like state are not available from an eval block

### ISSUE THREAD

**Issue by atoomic** [rurban/perl-compiler#303] opened 2015-10-28 22:43 UTC
When using features (like state), they are not available inside an eval block
we do not have the correct warning as they are not available

```
> perl -e 'use warnings; use feature ":5.10"; eval q/state ($a) = 1; 1/ or print $@ '
Initialization of state variables in list context currently forbidden at (eval 1) line 1, at EOF
> perlcc -r -e 'use warnings; use feature ":5.10"; eval q/state ($a) = 1; 1/ or print $@ '
/usr/local/cpanel/3rdparty/perl/522-debug/bin/perlcc: Unexpected compiler output
Undefined subroutine &main::state called at (eval 1) line 1.
```
Forcing to load the features inside the eval block fixes the issue
```
> perlcc -r -e 'use warnings; use feature ":5.10"; eval q/use feature ":5.10"; state ($a) = 1; 1/ or print $@ '
/usr/local/cpanel/3rdparty/perl/522-debug/bin/perlcc: Unexpected compiler output
Initialization of state variables in list context currently forbidden at (eval 1) line 1, at EOF
```

We cannot use state inside a quoted eval
````
> perl -e 'use warnings; use feature ":5.10"; eval q/sub foo { state $a; return ++$a }  1/ or print $@;  print foo(); print foo(); print "\n"'
12
> perlcc -r -e 'use warnings; use feature ":5.10"; eval q/sub foo { state $a; return ++$a }  1/ or print $@;  print foo(); print foo(); print "\n"'
Can't call method "state" on an undefined value at (eval 1) line 1.
````

**Comment by toddr** [comment] 2015-10-28 22:50
Dupe of #302

**Closed by toddr** 2015-10-28 22:50 UTC
