### ISSUE TITLE
constant modification causes segfault not die.

### ISSUE THREAD

**Issue by toddr** [rurban/perl-compiler#307] opened 2015-10-29 17:48 UTC
```perl
use constant roref=>\2;
eval { for (roref) { $_ = "world" } };
$@ =~ qr/Modification of a read-only value attempted/ and print "ok\n";
```

$>perl -e 'use constant roref=>\2; eval { for (roref) { $_ = "world" } }; $@ =~ qr/Modification of a read-only value attempted/ and print "ok\n";'
ok

$>perlcc -e 'use constant roref=>\2; eval { for (roref) { $_ = "world" } }; $@ =~ qr/Modification of a read-only value attempted/ and print "ok\n";'; ./a.out
zsh: segmentation fault  ./a.out

**Comment by atoomic** [comment] 2015-10-29 20:30
duplicate of 269

**Closed** 2015-10-29 20:30 UTC
Labels: CoreTests.522
