### ISSUE TITLE
Destruction error when using END block and fork

### ISSUE THREAD

**Issue by atoomic** [rurban/perl-compiler#271] opened 2015-10-21 20:55 UTC
Env: perl 5.22

````perl
> cat test.pl
#!./perl

my $FALSE = 0;
END { delete $ENV{'Boom'} if $FALSE }

my $kid = open my $fh, "-|";
if ($kid) { # parent
    my $read = <$fh>;
    close($fh) or die "cannot close pipe from kid proc: $!";
    print "ok\n";
}
else { # child
    print "$$\n";
    exit;
}
````

This works with -O0
````sh
> perl test.pl
ok
> perlcc test.pl && ./test
ok
````

but fails with -O3
````
> perlcc -O3 test.pl
> ./test
*** glibc detected *** ./test: free(): invalid pointer: 0x080e40a0 ***
======= Backtrace: =========
/lib/libc.so.6(+0x70b91)[0x20ab91]
/lib/libc.so.6(+0x732c3)[0x20d2c3]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_op_clear+0x534)[0x523df0]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_op_free+0x316)[0x523787]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_cv_undef_flags+0x407)[0x5dd10a]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_cv_undef+0x55)[0x5dccfd]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_sv_clear+0x423)[0x6f3c9e]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_sv_free2+0xed)[0x6f6570]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(+0x24e8b0)[0x74a8b0]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_leave_scope+0x217c)[0x751b24]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_pop_scope+0x58)[0x74aeab]
./test(fast_perl_destruct+0x28d)[0x80b076b]
./test(main+0x30a)[0x80b10b6]
/lib/libc.so.6(__libc_start_main+0xe6)[0x1b0d36]
./test[0x8049e11]
======= Memory map: ========
0013b000-0013e000 r-xp 00000000 fd:00 1047694    /lib/libdl-2.12.so
0013e000-0013f000 r--p 00002000 fd:00 1047694    /lib/libdl-2.12.so
0013f000-00140000 rw-p 00003000 fd:00 1047694    /lib/libdl-2.12.so
00140000-00168000 r-xp 00000000 fd:00 1047988    /lib/libm-2.12.so
00168000-00169000 r--p 00027000 fd:00 1047988    /lib/libm-2.12.so
00169000-0016a000 rw-p 00028000 fd:00 1047988    /lib/libm-2.12.so
0016a000-00171000 r-xp 00000000 fd:00 1047638    /lib/libcrypt-2.12.so
00171000-00172000 r--p 00007000 fd:00 1047638    /lib/libcrypt-2.12.so
00172000-00173000 rw-p 00008000 fd:00 1047638    /lib/libcrypt-2.12.so
00173000-0019a000 rw-p 00000000 00:00 0
0019a000-0032b000 r-xp 00000000 fd:00 1047504    /lib/libc-2.12.so
0032b000-0032d000 r--p 00190000 fd:00 1047504    /lib/libc-2.12.so
0032d000-0032e000 rw-p 00192000 fd:00 1047504    /lib/libc-2.12.so
0032e000-00331000 rw-p 00000000 00:00 0
00331000-0034e000 r-xp 00000000 fd:00 1048205    /lib/libgcc_s-4.4.7-20120601.so.1
0034e000-0034f000 rw-p 0001d000 fd:00 1048205    /lib/libgcc_s-4.4.7-20120601.so.1
004dc000-004fa000 r-xp 00000000 fd:00 1047368    /lib/ld-2.12.so
004fa000-004fb000 r--p 0001d000 fd:00 1047368    /lib/ld-2.12.so
004fb000-004fc000 rw-p 0001e000 fd:00 1047368    /lib/ld-2.12.so
004fc000-00937000 r-xp 00000000 fd:00 4067670    /usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so
00937000-0093d000 rw-p 0043b000 fd:00 4067670    /usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so
00964000-0097b000 r-xp 00000000 fd:00 1048103    /lib/libpthread-2.12.so
0097b000-0097c000 r--p 00016000 fd:00 1048103    /lib/libpthread-2.12.so
0097c000-0097d000 rw-p 00017000 fd:00 1048103    /lib/libpthread-2.12.so
0097d000-0097f000 rw-p 00000000 00:00 0
00c1c000-00c22000 r-xp 00000000 fd:00 1179648    /usr/lib/libgdbm.so.2.0.0
00c22000-00c23000 rw-p 00005000 fd:00 1179648    /usr/lib/libgdbm.so.2.0.0
00e82000-00e84000 r-xp 00000000 fd:00 1048115    /lib/libutil-2.12.so
00e84000-00e85000 r--p 00001000 fd:00 1048115    /lib/libutil-2.12.so
00e85000-00e86000 rw-p 00002000 fd:00 1048115    /lib/libutil-2.12.so
00e9f000-00eb6000 r-xp 00000000 fd:00 1047990    /lib/libnsl-2.12.so
00eb6000-00eb7000 r--p 00016000 fd:00 1047990    /lib/libnsl-2.12.so
00eb7000-00eb8000 rw-p 00017000 fd:00 1047990    /lib/libnsl-2.12.so
00eb8000-00eba000 rw-p 00000000 00:00 0
00ec7000-00ec8000 r-xp 00000000 00:00 0          [vdso]
00ecd000-00ecf000 r-xp 00000000 fd:00 1046746    /lib/libfreebl3.so
00ecf000-00ed0000 r--p 00001000 fd:00 1046746    /lib/libfreebl3.so
00ed0000-00ed1000 rw-p 00002000 fd:00 1046746    /lib/libfreebl3.so
08048000-080b6000 r-xp 00000000 fd:00 1600850    /root/workspace/bc/test
080b6000-080e5000 rw-p 0006e000 fd:00 1600850    /root/workspace/bc/test
080e5000-080e6000 rw-p 00000000 00:00 0
09372000-093b4000 rw-p 00000000 00:00 0          [heap]
b74bd000-b74be000 r--p 01083000 fd:00 1199664    /usr/lib/locale/locale-archive
b74be000-b75dc000 r--p 0019b000 fd:00 1199664    /usr/lib/locale/locale-archive
b75dc000-b77dc000 r--p 00000000 fd:00 1199664    /usr/lib/locale/locale-archive
b77dc000-b77df000 rw-p 00000000 00:00 0
b77e9000-b77ea000 rw-p 00000000 00:00 0
b77ea000-b77eb000 rw-p 00000000 00:00 0
bff01000-bff16000 rw-p 00000000 00:00 0          [stack]
cannot close pipe from kid proc:  at test.pl line 9.
*** glibc detected *** ./test: free(): invalid pointer: 0x080e40a0 ***
======= Backtrace: =========
/lib/libc.so.6(+0x70b91)[0x20ab91]
/lib/libc.so.6(+0x732c3)[0x20d2c3]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_op_clear+0x534)[0x523df0]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_op_free+0x316)[0x523787]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_cv_undef_flags+0x407)[0x5dd10a]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_cv_undef+0x55)[0x5dccfd]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_sv_clear+0x423)[0x6f3c9e]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_sv_free2+0xed)[0x6f6570]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(+0x24e8b0)[0x74a8b0]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_leave_scope+0x217c)[0x751b24]
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so(Perl_pop_scope+0x58)[0x74aeab]
./test(fast_perl_destruct+0x28d)[0x80b076b]
./test(main+0x30a)[0x80b10b6]
/lib/libc.so.6(__libc_start_main+0xe6)[0x1b0d36]
./test[0x8049e11]
======= Memory map: ========
0013b000-0013e000 r-xp 00000000 fd:00 1047694    /lib/libdl-2.12.so
0013e000-0013f000 r--p 00002000 fd:00 1047694    /lib/libdl-2.12.so
0013f000-00140000 rw-p 00003000 fd:00 1047694    /lib/libdl-2.12.so
00140000-00168000 r-xp 00000000 fd:00 1047988    /lib/libm-2.12.so
00168000-00169000 r--p 00027000 fd:00 1047988    /lib/libm-2.12.so
00169000-0016a000 rw-p 00028000 fd:00 1047988    /lib/libm-2.12.so
0016a000-00171000 r-xp 00000000 fd:00 1047638    /lib/libcrypt-2.12.so
00171000-00172000 r--p 00007000 fd:00 1047638    /lib/libcrypt-2.12.so
00172000-00173000 rw-p 00008000 fd:00 1047638    /lib/libcrypt-2.12.so
00173000-0019a000 rw-p 00000000 00:00 0
0019a000-0032b000 r-xp 00000000 fd:00 1047504    /lib/libc-2.12.so
0032b000-0032d000 r--p 00190000 fd:00 1047504    /lib/libc-2.12.so
0032d000-0032e000 rw-p 00192000 fd:00 1047504    /lib/libc-2.12.so
0032e000-00331000 rw-p 00000000 00:00 0
00331000-0034e000 r-xp 00000000 fd:00 1048205    /lib/libgcc_s-4.4.7-20120601.so.1
0034e000-0034f000 rw-p 0001d000 fd:00 1048205    /lib/libgcc_s-4.4.7-20120601.so.1
004dc000-004fa000 r-xp 00000000 fd:00 1047368    /lib/ld-2.12.so
004fa000-004fb000 r--p 0001d000 fd:00 1047368    /lib/ld-2.12.so
004fb000-004fc000 rw-p 0001e000 fd:00 1047368    /lib/ld-2.12.so
004fc000-00937000 r-xp 00000000 fd:00 4067670    /usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so
00937000-0093d000 rw-p 0043b000 fd:00 4067670    /usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/CORE/libperl.so
00964000-0097b000 r-xp 00000000 fd:00 1048103    /lib/libpthread-2.12.so
0097b000-0097c000 r--p 00016000 fd:00 1048103    /lib/libpthread-2.12.so
0097c000-0097d000 rw-p 00017000 fd:00 1048103    /lib/libpthread-2.12.so
0097d000-0097f000 rw-p 00000000 00:00 0
00c1c000-00c22000 r-xp 00000000 fd:00 1179648    /usr/lib/libgdbm.so.2.0.0
00c22000-00c23000 rw-p 00005000 fd:00 1179648    /usr/lib/libgdbm.so.2.0.0
00e82000-00e84000 r-xp 00000000 fd:00 1048115    /lib/libutil-2.12.so
00e84000-00e85000 r--p 00001000 fd:00 1048115    /lib/libutil-2.12.so
00e85000-00e86000 rw-p 00002000 fd:00 1048115    /lib/libutil-2.12.so
00e9f000-00eb6000 r-xp 00000000 fd:00 1047990    /lib/libnsl-2.12.so
00eb6000-00eb7000 r--p 00016000 fd:00 1047990    /lib/libnsl-2.12.so
00eb7000-00eb8000 rw-p 00017000 fd:00 1047990    /lib/libnsl-2.12.so
00eb8000-00eba000 rw-p 00000000 00:00 0
00ec7000-00ec8000 r-xp 00000000 00:00 0          [vdso]
00ecd000-00ecf000 r-xp 00000000 fd:00 1046746    /lib/libfreebl3.so
00ecf000-00ed0000 r--p 00001000 fd:00 1046746    /lib/libfreebl3.so
00ed0000-00ed1000 rw-p 00002000 fd:00 1046746    /lib/libfreebl3.so
08048000-080b6000 r-xp 00000000 fd:00 1600850    /root/workspace/bc/test
080b6000-080e5000 rw-p 0006e000 fd:00 1600850    /root/workspace/bc/test
080e5000-080e6000 rw-p 00000000 00:00 0
09372000-093b4000 rw-p 00000000 00:00 0          [heap]
b74bc000-b74bd000 rw-p 00000000 00:00 0
b74bd000-b74be000 r--p 01083000 fd:00 1199664    /usr/lib/locale/locale-archive
b74be000-b75dc000 r--p 0019b000 fd:00 1199664    /usr/lib/locale/locale-archive
b75dc000-b77dc000 r--p 00000000 fd:00 1199664    /usr/lib/locale/locale-archive
b77dc000-b77df000 rw-p 00000000 00:00 0
b77ea000-b77eb000 rw-p 00000000 00:00 0
bff01000-bff16000 rw-p 00000000 00:00 0          [stack]
Aborted
````

**Comment by toddr** [comment] 2015-10-29 21:07
./t/testc.sh 271

**Comment by toddr** [comment] 2015-10-29 23:06
I'm making this a high only because it should be easily solvable if we know it's working on -O0

**Comment by toddr** [comment] 2015-10-30 16:17
also passes with -O2.

**Comment by toddr** [comment] 2015-10-30 16:20
These look like bugs.

```
lib/B/C/OverLoad/B/CV.pm:                    "  HEK *lexhek = share_hek(savepvn(%s, %d), %d, 0);",
lib/B/C/OverLoad/B/CV.pm:            init()->add( savepvn( "CvFILE($sym)", $cv->FILE ) );
lib/B/C/OverLoad/B/CV.pm:                    "SvPVX(&sv_list[%d]) = savepvn(%s, %u);",
lib/B/C/OverLoad/B/IO.pm:            init()->add( sprintf( "Io%s(%s) = savepvn(%s, %u);", $field, $sym, cstring($fsym), length $fsym ) );
```

**Comment by toddr** [comment] 2015-10-30 16:25
Also in master
```
lib/B/C.pm:      push @init, sprintf( "%s = savepvn(%s, %u);", $dest, $cstr, $cur );
lib/B/C.pm:                    sprintf("  HEK *lexhek = share_hek(savepvn(%s, %d), %d, 0);",
lib/B/C.pm:      $init->add( sprintf("SvPVX(&sv_list[%d]) = savepvn(%s, %u);",
lib/B/C.pm:    $init->add(sprintf("Io%s(%s) = savepvn(%s, %u);", $field, $sym,
```

**Comment by toddr** [comment] 2015-10-30 17:03
Grr... ok we really shouldn't have a subroutine with the same name as a perl macro. That's a little confusing. These look fine in light of that realization.

**Comment by toddr** [comment] 2015-10-30 17:10
O2 it's a null byte. O3 it's a string?
```
#O2
{&xpvmg_list[0], 1, 0x600007, {0}},
# O3
Static const char pv2[] = "";
{&xpvmg_list[0], 1, 0x600007, {.svu_pv = (char *) pv2}},
```

**Comment by toddr** [comment] 2015-10-30 17:27
#306 may be a different incarnation of the same bug.

**Comment by toddr** [comment] 2015-11-02 19:02
heh. Confirmed. The fix for 306 corrects everything but this
```
op/attrhand.t                PLAN      BC issue #271 - Attribute::Handlers
```

**Comment by toddr** [comment] 2015-11-02 19:04
Our commit looks like this and appears sugiccient.

**Comment by toddr** [comment] 2015-11-02 19:19
This is a dupe of #306

**Closed by toddr** 2015-11-02 19:19 UTC
Labels: CoreTests.522, Priority-High
