### ISSUE TITLE
B::C perl5.20.2 URI.pm problem

### ISSUE THREAD

**Issue by sten22** [rurban/perl-compiler#199] opened 2015-05-12 02:26 UTC
## test script
```perl
use strict; use warnings;
use URI;

#preload modules
use URI::_generic;
use URI::_foreign;
use URI::http;
use URI::_server;
use Data::Dumper;

my $url = URI->new('http://127.0.0.1/path');

my $url2 = URI->new($url);

warn Dumper([$url, $url->path, $url2, $url2->path]);
```
## expected output
also same output using compiled version with 5.14.4
```
# perl uri.pl 
$VAR1 = [
          bless( do{\(my $o = 'http://127.0.0.1/path')}, 'URI::http' ),
          '/path',
          bless( do{\(my $o = 'http://127.0.0.1/path')}, 'URI::http' ),
          '/path'
        ];
```

## compiled output using 5.20.2
```
bash-4.2# perlcc uri.pl
bash-4.2# ./uri 
$VAR1 = [
          bless( do{\(my $o = 'http://127.0.0.1/path')}, 'URI::http' ),
          '/path',
          bless( do{\(my $o = 'URI::http=SCALAR(0x949840)')}, 'URI::_foreign' ),
          ':http=SCALAR(0x949840)'
        ];
```

**Comment by sten22** [comment] 2015-05-12 03:41
After investigation I found real problem is that overload not work:
```
bash-4.2# cat overload.pl
package Test;
use overload '""' => sub { 42 };

sub new {
  bless {}, shift;
};

package main;
warn Test->new;
bash-4.2# perl overload.pl
42 at overload.pl line 9.
bash-4.2# perlcc -S -r overload.pl 
Test=HASH(0x1579f68) at overload.pl line 9.
```

**Comment by rurban** [comment] 2015-05-12 06:30
Yes,  this is a good explanation.  Thanks.  I'll look at it later,  when I start on the 5.22 port

**Comment by sten22** [comment] 2015-05-17 02:57
same on 5.18.4
works till 5.16.3

**Comment by rurban** [comment] 2015-05-17 10:28
Summary: String overload broken since 5.18

**Comment by sten22** [comment] 2015-05-17 14:14
not only string, any overload not work:
```
bash-4.2# perl overload_number.pl 
42 at overload_number.pl line 3.
bash-4.2# perlcc overload_number.pl 
bash-4.2# ./overload_number 
54266352 at overload_number.pl line 3.
bash-4.2# cat overload_number.pl
use overload '*' => sub { 42 };
bless $a = {}, 'main';
warn $a * 2;
```

**Comment by rurban** [comment] 2015-10-30 08:32
Duplicate of GH #219, tracking it there.

**Comment by toddr** [comment] 2015-11-05 22:17
Closing this as a duplicate of #219

**Closed by toddr** 2015-11-05 22:17 UTC
